# .github/dependabot.yml
# Basic Dependabot configuration for NuGet and GitHub Actions

version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    # Look for *.csproj files in the root directory and subdirectories
    directory: "/" 
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "monday" # Optional: specify day of the week
    # Add labels to Dependabot pull requests
    labels:
      - "dependencies"
      - "nuget"
    # Limit to 5 open PRs for NuGet
    open-pull-requests-limit: 5

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for workflow files in the .github/workflows directory
    directory: "/" 
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "monday"
    # Add labels to Dependabot pull requests
    labels:
      - "dependencies"
      - "github-actions"
    # Limit to 5 open PRs for Actions
    open-pull-requests-limit: 5 