name: Docker Publish - Migrator Runner

on:
  push:
    tags:
      - 'v*.*.*' # Trigger ONLY on tags like v1.0.0
    # Optional: Keep paths filter if you only want tags associated with
    # changes in these paths to trigger a build.
    # paths:
    #   - 'src/Migrator.Runner/**' 
    #   - 'src/Migrator.Core/**'   
    #   - '.github/workflows/docker-publish.yml' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      packages: write 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: bthdev/db-migration-runner # Use the specified Docker Hub repo name
        tags: |
          # Git tag vX.Y.Z: Create X.Y.Z tag and also update latest
          type=semver,pattern={{version}} 
          type=raw,value=latest # Since we only trigger on tags, always update latest

          # Short commit SHA for traceability
          type=sha,prefix=sha-,suffix=,format=short 

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: src/Migrator.Runner/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}